# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.4
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: aadityanikam2004@gmail.com
author_name: AdityaNik
cloud_provider: vercel
contract_name: swap_contract
preset_name: production
project_name: algoswap

